### ISSUE TITLE
Some issues with the AutoRegLib-1.7-52 core for Quark

### ISSUE THREAD

**Issue by Ztritsval** [Reforged333/Sodium-Reloaded#1]
After loading the game it gives me a report about a non-identical crash in-game
![изображение_2022-01-27_173826](https://user-images.githubusercontent.com/98527369/151352336-a2c80f9f-a15a-4d79-a8a0-49fc0dccb439.png)
 from AutoRegLib-1.7-52

**Comment by KKotik** [comment]
https://github.com/Someone-Else-Was-Taken/Magnesium/issues/3
That might be helpful also.
