### ISSUE TITLE
Black instead of alpha

### ISSUE THREAD

**Issue by LaBestiaBrutal** [Reforged333/Sodium-Reloaded#2]
Visual glitch that shows on some of the modded lights, crops and some other items, it just shows black 2D squares instead of transparencies.

Log:
https://gist.github.com/LaBestiaBrutal/40495b005aaa96adeaa05dbfce915e28

**Comment by Atlantispy** [comment]
Can confirm, happening with croptopia crops at least.

**Comment by Reforged333** [comment]
The issue has been resolved in the coming update.
thanks.
