### ISSUE TITLE
Differences between Sodium Reloaded and Magnesium?

### ISSUE THREAD

**Issue by itsdinkd** [Reforged333/Sodium-Reloaded#3]

**Comment by Reforged333** [comment]
Magnesium is OUT-DATED + Creates a lot of bad compatibility and someoneelsewastaken forget it + Magnesium doesn't support 1.18.1.

**Comment by itsdinkd** [comment]
Hmm.. we tried putting this in my modpack, and it crashed on launch 

https://paste.corebot.dev/sumizoquge.rb
