### ISSUE TITLE
Please change the project name and icon

### ISSUE THREAD

**Issue by jellysquid3** [Reforged333/Sodium-Reloaded#8]
Hi. I am the author of the original project here.

Per usual-- and this really shouldn't be a usual thing but here we are anyways-- I am now asking in a public manner that you stop using our name/icons for your unaffiliated project. I don't feel like writing an essay about the problems with this because [we've had one in our FAQ for months now](https://github.com/CaffeineMC/caffeine-meta/wiki/FAQ#where-are-the-forge-versions-of-your-mods) and I find myself explaining this far too often.

The puzzling thing here to me is that you asked multiple times over Discord, even spamming me by creating and deleting messages repeatedly, and despite me asking you multiple times not to use our branding, that doesn't appear to have changed anything.

<details>
<summary>Discord message log</summary>
<img src="https://user-images.githubusercontent.com/1363084/151672955-00336631-42e3-401e-b0d5-e5212ee1fb33.png" />
</details>

Evidently you seem to care what I think at least a little bit, so could you please do what little I am asking here? Use a unique project name/icon... that's all.

**Comment by mosharky** [comment]
yikes. not only did he make an odd decision to not listen, but he decided to essentially spam your dms because he couldn't wait any longer than a few hours lmao

im not sure why he considers those names "perfect", he could literally look at the periodic table and choose any other name for his ports

**Comment by Reforged333** [comment]
i will change the name.
+
the icon soon.
.
